table dim_customers
	lineageTag: 1b286f34-dfa5-4174-a826-2de5320d940b

	measure AOV = ```
			
			    sum(fct_orders[Total Sales]) / count(fct_orders[ORDER_ID])
			```
		displayFolder: _measures
		lineageTag: d37dd113-c936-4ba3-97d5-fdfced869ead

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales YoY%' =
			
			VAR __PREV_YEAR =
				CALCULATE(
					SUM('fct_orders'[Total Sales]),
					DATEADD('dim_date'[Date], -1, YEAR)
				)
			RETURN
				DIVIDE(SUM('fct_orders'[Total Sales]) - __PREV_YEAR, __PREV_YEAR)
		formatString: 0%;-0%;0%
		displayFolder: _measures
		lineageTag: c5f399bb-a8de-4165-8f96-66644724251d

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "YearOverYear"
				}

		changedProperty = FormatString

	measure 'Total Sales QoQ%' =
			
			VAR __PREV_QUARTER =
				CALCULATE(
					SUM('fct_orders'[Total Sales]),
					DATEADD('dim_date'[Date], -1, QUARTER)
				)
			RETURN
				DIVIDE(SUM('fct_orders'[Total Sales]) - __PREV_QUARTER, __PREV_QUARTER)
		formatString: 0%;-0%;0%
		displayFolder: _measures
		lineageTag: ec785fde-254a-42aa-a66a-7a8ab5ee0dd0

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "QuarterOverQuarter"
				}

		changedProperty = FormatString

	measure 'Total Sales MoM%' =
			
			VAR __PREV_MONTH =
				CALCULATE(
					SUM('fct_orders'[Total Sales]),
					DATEADD('dim_date'[Date], -1, MONTH)
				)
			RETURN
				DIVIDE(SUM('fct_orders'[Total Sales]) - __PREV_MONTH, __PREV_MONTH)
		formatString: 0%;-0%;0%
		displayFolder: _measures
		lineageTag: a194e946-7aaa-49a4-869f-8e335a701fef

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MonthOverMonth"
				}

		changedProperty = FormatString

	measure 'AOV YoY%' =
			
			VAR __PREV_YEAR = CALCULATE([AOV], DATEADD('dim_date'[Date], -1, YEAR))
			RETURN
				DIVIDE([AOV] - __PREV_YEAR, __PREV_YEAR)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _measures
		lineageTag: cc82c960-b592-43e9-adec-24e1dfab4ed6

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "YearOverYear"
				}

		changedProperty = FormatString

	measure 'AOV QoQ%' =
			
			VAR __PREV_QUARTER = CALCULATE([AOV], DATEADD('dim_date'[Date], -1, QUARTER))
			RETURN
				DIVIDE([AOV] - __PREV_QUARTER, __PREV_QUARTER)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _measures
		lineageTag: f436a50a-6176-4fe4-b85e-aa8d87c0afe1

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "QuarterOverQuarter"
				}

		changedProperty = FormatString

	measure 'AOV MoM%' =
			
			VAR __PREV_MONTH = CALCULATE([AOV], DATEADD('dim_date'[Date], -1, MONTH))
			RETURN
				DIVIDE([AOV] - __PREV_MONTH, __PREV_MONTH)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _measures
		lineageTag: 02aa19b1-1426-4d1b-9b2d-bac3768c9b41

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MonthOverMonth"
				}

		changedProperty = FormatString

	measure 'Number of Orders YoY%' =
			
			VAR __PREV_YEAR =
				CALCULATE(
					COUNTA('fct_orders'[ORDER_ID]),
					DATEADD('dim_date'[Date], -1, YEAR)
				)
			RETURN
				DIVIDE(COUNTA('fct_orders'[ORDER_ID]) - __PREV_YEAR, __PREV_YEAR)
		formatString: 0%;-0%;0%
		displayFolder: _measures
		lineageTag: 9e2415d9-e7a3-4d12-8b66-44aca1900535

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "YearOverYear"
				}

		changedProperty = FormatString

	/// Number of Orders QoQ%
	measure 'Number of Orders QoQ%' =
			
			VAR __PREV_QUARTER =
				CALCULATE(
					COUNTA('fct_orders'[ORDER_ID]),
					DATEADD('dim_date'[Date], -1, QUARTER)
				)
			RETURN
				DIVIDE(COUNTA('fct_orders'[ORDER_ID]) - __PREV_QUARTER, __PREV_QUARTER)
		formatString: 0%;-0%;0%
		displayFolder: _measures
		lineageTag: 37ddfd00-0236-4af7-944d-dff9a4f78a16

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "QuarterOverQuarter"
				}

		changedProperty = FormatString

	measure 'Number of Orders MoM%' =
			
			VAR __PREV_MONTH =
				CALCULATE(
					COUNTA('fct_orders'[ORDER_ID]),
					DATEADD('dim_date'[Date], -1, MONTH)
				)
			RETURN
				DIVIDE(COUNTA('fct_orders'[ORDER_ID]) - __PREV_MONTH, __PREV_MONTH)
		formatString: 0%;-0%;0%
		displayFolder: _measures
		lineageTag: 683c29dc-8f01-4448-8a26-e66b301b1f38

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MonthOverMonth"
				}

		changedProperty = FormatString

	measure 'Number of campaigns' = count(fct_orders[CAMPAIGN_ID])
		formatString: 0
		displayFolder: _measures
		lineageTag: 42922aa4-8be7-48cb-99da-f4fac168ab73

	measure Funnel_Starts =
			
			CALCULATE(
			    DISTINCTCOUNT(dim_sessions[ACTIVITY_ID]),
			    dim_sessions[event_page] = "Home page"
			)
		formatString: 0
		displayFolder: _measures
		lineageTag: 752fc644-957e-4a36-b50c-1c28aafd4cd5

	measure Funnel_final =
			
			CALCULATE(
			    DISTINCTCOUNT(dim_sessions[ACTIVITY_ID]),
			    dim_sessions[event_page] = "Payments"
			)
		formatString: 0
		displayFolder: _measures
		lineageTag: 19ebbeed-3000-428c-aef5-803dbf935645

	measure 'Conversion rate' = ```
			
			    DIVIDE([Funnel_final], [Funnel_Starts], 0)
			```
		formatString: 0%;-0%;0%
		displayFolder: _measures
		lineageTag: b937e5e4-184d-463d-9a40-5428ae99ace2

	column CUSTOMER_ID
		dataType: string
		lineageTag: fd79e4e9-be17-47c5-88a0-c62c93323700
		summarizeBy: none
		sourceColumn: CUSTOMER_ID

		annotation SummarizationSetBy = Automatic

	column FIRST_NAME
		dataType: string
		lineageTag: 5a6f9eeb-47c3-4b80-bfa2-c8b42c7f33e8
		summarizeBy: none
		sourceColumn: FIRST_NAME

		annotation SummarizationSetBy = Automatic

	column LAST_NAME
		dataType: string
		lineageTag: 4e2c8292-9fa9-4ca6-bf30-777e9ac03fb9
		summarizeBy: none
		sourceColumn: LAST_NAME

		annotation SummarizationSetBy = Automatic

	column GENDER
		dataType: string
		lineageTag: 07c164a7-f184-413f-8d62-a7b40fe28edd
		summarizeBy: none
		sourceColumn: GENDER

		annotation SummarizationSetBy = Automatic

	column DOB
		dataType: dateTime
		formatString: Short Date
		lineageTag: df44bfbe-24e6-484f-8535-b557244945aa
		summarizeBy: none
		sourceColumn: DOB

		variation Variation
			isDefault
			relationship: 08481964-9833-4910-8444-4a268fffe01e
			defaultHierarchy: LocalDateTable_0cb47ba6-3574-4925-97ec-d59abf854291.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column REGISTRATION_DATE
		dataType: dateTime
		formatString: Short Date
		lineageTag: a6996ee0-244b-4c35-ae6f-66d20382e81e
		summarizeBy: none
		sourceColumn: REGISTRATION_DATE

		variation Variation
			isDefault
			relationship: b8fba6b8-f79c-40fa-a179-ca3a289e5eb0
			defaultHierarchy: LocalDateTable_626c8451-38b3-4552-93b3-142d8ac5484f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CITY
		dataType: string
		lineageTag: 73e16ed4-4c94-495c-b54b-4250bb81a87d
		summarizeBy: none
		sourceColumn: CITY

		annotation SummarizationSetBy = Automatic

	column Age = DATEDIFF([DOB], TODAY(), YEAR)
		dataType: int64
		formatString: 0
		lineageTag: 09ef49d3-978f-4d84-bf7a-d726fed429b5
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Age Range' =
			
			SWITCH(TRUE(),
			    dim_customers[Age] < 20, "< 20",
			    dim_customers[Age] <= 30, "20-30",
			    dim_customers[Age] <= 40, "30-40",
			    dim_customers[Age] <= 50, "40-50",
			    dim_customers[Age] <= 60, "50-60",
			    dim_customers[Age] <= 70, "60-70",
			    "70+"
			)
		lineageTag: d87eb8a6-0f05-4718-97b2-0d1c74fb3a2a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dim_customers = m
		mode: import
		source =
				let
				    Source = STG_CUSTOMERS,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"EMAIL"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

