table fct_orders
	lineageTag: 05d3a6c9-6aae-48ab-beef-1e05e3eadbbf

	column ORDER_ID
		dataType: double
		lineageTag: c4a3ea75-b157-46b2-9819-e79c2acf206b
		summarizeBy: none
		sourceColumn: ORDER_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ORDER_DATE
		dataType: dateTime
		formatString: Short Date
		lineageTag: b6d10a65-9f86-442b-80eb-952a6aafb920
		summarizeBy: none
		sourceColumn: ORDER_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CUSTOMER_ID
		dataType: string
		lineageTag: 7203fe48-6526-45d5-9dc5-eaa76ce71200
		summarizeBy: none
		sourceColumn: CUSTOMER_ID

		annotation SummarizationSetBy = Automatic

	column YEAR_MONTH
		dataType: string
		lineageTag: aff0416a-e8c1-46e3-9daa-bf9a04fb8058
		summarizeBy: none
		sourceColumn: YEAR_MONTH

		annotation SummarizationSetBy = Automatic

	column 'Total Sales'
		dataType: double
		formatString: #,0.00
		lineageTag: 39ac8d32-e1d8-41cc-91b0-8aa7e1cf29f6
		summarizeBy: sum
		sourceColumn: Total Sales

		annotation SummarizationSetBy = Automatic

	column SHIPPING_FEE_TOTAL
		dataType: double
		lineageTag: e6a3bbb7-c12a-403f-9ab4-c5d69053ec89
		summarizeBy: sum
		sourceColumn: SHIPPING_FEE_TOTAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COMMISSION_TOTAL
		dataType: double
		lineageTag: 734d2198-c3c6-4022-8ace-0a4783c71517
		summarizeBy: sum
		sourceColumn: COMMISSION_TOTAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MAINTENANCE_TOTAL
		dataType: double
		lineageTag: 8f888901-a97e-48de-978a-2efd4af2ebfc
		summarizeBy: sum
		sourceColumn: MAINTENANCE_TOTAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TOTAL_AMOUNT
		dataType: double
		formatString: #,0.00
		lineageTag: 5008fe8b-2e86-4915-a0c5-a2631b919af5
		summarizeBy: sum
		sourceColumn: TOTAL_AMOUNT

		annotation SummarizationSetBy = Automatic

	column CAMPAIGN_ID
		dataType: string
		lineageTag: 94e86885-3903-467c-94d7-1b0390c3a780
		summarizeBy: none
		sourceColumn: CAMPAIGN_ID

		annotation SummarizationSetBy = Automatic

	partition fct_orders = m
		mode: import
		source =
				let
				    Source = STG_ORDERS,
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"SUBTOTAL_AMOUNT", "Total Sales"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"ORDER_DAY"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

